/**
 * Emitter: canonical project shape → data/*.js + data/*.css files in the
 * target project directory. Output is plain ES5/var-style JS to match the
 * rest of Nib (no bundler, loaded via <script> tag).
 */

const fs = require('fs');
const path = require('path');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function jsLiteral(value, indent = 0) {
  return JSON.stringify(value, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : ' '.repeat(indent) + line))
    .join('\n');
}

function writeFile(target, content) {
  ensureDir(path.dirname(target));
  fs.writeFileSync(target, content);
}

// ── pages → SECTIONS ───────────────────────────────────────────────────────
// Two-level drawer: parent-less pages become sections; pages with a parent
// become items under that section. Pages with a deeper parent attach to the
// nearest ancestor section.
function buildSections(pages) {
  const byId = new Map(pages.map((p) => [p.id, p]));
  const sectionOf = (id) => {
    let cur = byId.get(id);
    const seen = new Set();
    while (cur && cur.parent && !seen.has(cur.id)) {
      seen.add(cur.id);
      cur = byId.get(cur.parent);
    }
    return cur || null;
  };

  const sections = [];
  const sectionIndex = new Map();

  for (const page of pages) {
    if (!page.parent) {
      const section = {
        id: page.id,
        label: page.label,
        epic: '',
        items: [{ file: page.id, label: page.label, type: 'page' }],
      };
      sections.push(section);
      sectionIndex.set(page.id, section);
    }
  }

  for (const page of pages) {
    if (!page.parent) continue;
    const root = sectionOf(page.id);
    if (!root) continue;
    const section = sectionIndex.get(root.id);
    if (!section) continue;
    if (section.items.some((i) => i.file === page.id)) continue;
    section.items.push({ file: page.id, label: page.label, type: 'page' });
  }

  // Section with only its own header item is fine; drop empty sections defensively.
  return sections.filter((s) => s.items.length > 0);
}

// ── personas → STORY_MAP-ish persona records ───────────────────────────────
function buildPersonaIndex(personas) {
  const out = {};
  for (const p of personas) {
    out[p.id] = {
      label: p.label,
      role: p.role,
      org: p.org,
      initials: p.initials,
      color: p.color,
      summary: p.summary,
      jtbd: Array.isArray(p.jtbd) ? p.jtbd : [],
      pains: Array.isArray(p.pains) ? p.pains : [],
      goals: Array.isArray(p.goals) ? p.goals : [],
    };
  }
  return out;
}

// ── tokens → CSS :root block ───────────────────────────────────────────────
function tokensToCss(tokens) {
  const entries = Object.entries(tokens || {});
  if (!entries.length) {
    return '/* Generated by nib-ingest. No token overrides defined in workbook. */\n';
  }
  const lines = entries.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return `/* Generated by nib-ingest. Edit the workbook \`tokens\` tab to change. */\n:root {\n${lines}\n}\n`;
}

// ── main entry ─────────────────────────────────────────────────────────────
/**
 * @param {object} project Canonical project shape from build.js
 * @param {object} sourceMeta { kind, path, mtime } from the adapter
 * @param {string} outDir Project root to emit into
 * @returns {{ written: string[] }}
 */
function emit(project, sourceMeta, outDir) {
  const dataDir = path.join(outDir, 'data');
  ensureDir(dataDir);

  const written = [];
  const wrote = (rel, contents) => {
    const full = path.join(outDir, rel);
    writeFile(full, contents);
    written.push(rel);
  };

  // wireframe-config.js
  const wfConfigSrc = `/* Generated by nib-ingest. Edit the workbook \`meta\` tab to change. */
window.WIREFRAME_CONFIG = ${jsLiteral(project.meta)};
`;
  wrote('data/wireframe-config.js', wfConfigSrc);

  // sections.js
  const sections = buildSections(project.pages || []);
  wrote(
    'data/sections.js',
    `/* Generated by nib-ingest. Edit the workbook \`pages\` tab to change. */
var SECTIONS = ${jsLiteral(sections)};
window.SECTIONS = SECTIONS;
`
  );

  // tokens.css
  wrote('data/tokens.css', tokensToCss(project.tokens));

  // personas.js
  const personaIndex = buildPersonaIndex(project.personas || []);
  wrote(
    'data/personas.js',
    `/* Generated by nib-ingest. Edit the workbook \`personas\` tab to change. */
window.PERSONAS = ${jsLiteral(personaIndex)};
window.STORY_MAP = window.STORY_MAP || {};
`
  );

  // stories.js → DESIGN_STORIES (kind=design) + STORY_TITLES (everyone else)
  const stories = project.stories || [];
  const designStories = stories.filter((s) => s.kind === 'design');
  const storyTitles = {};
  for (const s of stories) storyTitles[s.id] = s.title;
  wrote(
    'data/stories.js',
    `/* Generated by nib-ingest. Edit the workbook \`stories\` tab to change. */
window.DESIGN_STORIES = ${jsLiteral(designStories)};
window.STORY_TITLES = ${jsLiteral(storyTitles)};
`
  );

  // blueprints/<flowId>.js — one per flow
  for (const [flowId, flow] of Object.entries(project.blueprints || {})) {
    wrote(
      `data/blueprints/${flowId}.js`,
      `/* Generated by nib-ingest. Edit the \`${flowId}\` tab to change. */
window.NIB_BLUEPRINTS = window.NIB_BLUEPRINTS || {};
window.NIB_BLUEPRINTS[${JSON.stringify(flowId)}] = ${jsLiteral(flow)};
`
    );
  }

  // blueprints/_index.js — list of flow ids in tree order (root → children)
  const flowIds = Object.keys(project.blueprints || {});
  const tree = buildBlueprintTree(project.blueprints || {});
  wrote(
    'data/blueprints/_index.js',
    `/* Generated by nib-ingest. Drives the blueprint hierarchy / Overview drill-down. */
window.NIB_BLUEPRINT_INDEX = ${jsLiteral({ ids: flowIds, tree })};
`
  );

  // registries/<name>.js — one per registry
  for (const [name, data] of Object.entries(project.registries || {})) {
    wrote(
      `data/registries/${name}.js`,
      `/* Generated by nib-ingest. Edit the \`_${name}\` tab to change. */
window.NIB_REGISTRIES = window.NIB_REGISTRIES || {};
window.NIB_REGISTRIES[${JSON.stringify(name)}] = ${jsLiteral(data)};
`
    );
  }

  // source-of-truth.txt — idempotent sidecar
  const sotLines = [
    `Source: ${sourceMeta.kind}`,
    `Location: ${sourceMeta.path || sourceMeta.url || '(unknown)'}`,
    sourceMeta.mtime ? `Last modified: ${sourceMeta.mtime}` : null,
    `Tabs ingested: ${(sourceMeta.tabsIngested || []).join(', ')}`,
  ].filter(Boolean);
  wrote('data/source-of-truth.txt', sotLines.join('\n') + '\n');

  return { written };
}

function buildBlueprintTree(blueprints) {
  const childrenOf = {};
  const roots = [];
  for (const [id, flow] of Object.entries(blueprints)) {
    const parent = flow.meta && flow.meta.parent;
    if (parent) {
      (childrenOf[parent] = childrenOf[parent] || []).push(id);
    } else {
      roots.push(id);
    }
  }
  const node = (id) => ({ id, children: (childrenOf[id] || []).map(node) });
  return roots.map(node);
}

module.exports = { emit, buildSections, buildBlueprintTree };
